version: '3'
services:
  db:
    image: postgres:15.2
    container_name: my_postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: SOACourse
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always
    ports:
      - "5431:5432"


  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springsoapapi
    ports:
      - "8000:8080"
    environment:
      db-url: jdbc:postgresql://db:5431/SOACourse
      db-username: postgres
      db-password: postgres
    depends_on:
      - db
    links:
      - db
    restart: always

