version: '3'

# Once you use the Network tag and put both the containers on the same network you will use the internal ports not the public one cause you have created a bridge
services:
  backend:
     build:
       context: .
       dockerfile: Dockerfile
     container_name: springsoapapi
     ports:
       - "8080:8080"
     environment:
       db-url: jdbc:postgresql://db:5432/SOACourse
       db-username: postgres
       db-password: postgres
     depends_on:
       - db
     networks:
       - mynet
     restart: always

  db:
    image: postgres:15.2
    container_name: my_postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: SOACourse
    networks:
      - mynet
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.txt
      - ./pgdata:/var/lib/postgresql/data
    restart: always
    ports:
      - "5431:5432"


networks:
  mynet:
    driver: bridge
